# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_day', models.DateTimeField(auto_now_add=True)),
                ('end_day', models.DateTimeField(auto_now_add=True)),
                ('remain_day', models.PositiveIntegerField(default=0)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
