# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20180217_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他')], default='O', max_length=10, null=True),
        ),
    ]
