# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 07:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20180225_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='餘額'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='end_day',
            field=models.DateTimeField(auto_now_add=True, verbose_name='到期日期'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他')], default='O', max_length=10, null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='remain_day',
            field=models.PositiveIntegerField(default=0, verbose_name='剩餘天數'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='註冊日期'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_day',
            field=models.DateTimeField(auto_now_add=True, verbose_name='開始日期'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '一般會員'), (1, '黃金會員'), (2, '白金會員'), (3, '鑽石會員')], default=0, verbose_name='會員等級'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='會員'),
        ),
    ]
