# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strategy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_category',
            name='modify_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='s_level',
            name='modify_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
