# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strategy', '0004_auto_20180218_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='path',
        ),
        migrations.AlterField(
            model_name='strategy',
            name='category',
            field=models.CharField(choices=[('bull', '多頭'), ('bear', '空頭')], max_length=255),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='files_dir',
            field=models.FileField(null=True, upload_to='strategies/bull/normal'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='level',
            field=models.CharField(choices=[('normal', '普通'), ('golden', '黃金'), ('platinum', '白金'), ('diamond', '鑽石')], max_length=255),
        ),
        migrations.DeleteModel(
            name='s_category',
        ),
        migrations.DeleteModel(
            name='s_level',
        ),
    ]
