# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 14:25
from __future__ import unicode_literals

import Strategy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strategy', '0005_auto_20180218_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='files_dir',
            field=models.FileField(null=True, upload_to=Strategy.models.file_path),
        ),
    ]
