# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='img_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
