# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contents', models.TextField()),
                ('send_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
