# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contents',
            field=models.TextField(verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='客戶信箱'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(max_length=255, verbose_name='客戶名稱'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='發送日期'),
        ),
    ]
